FORMAT: 1A
HOST: http://splapi.retrorocket.biz

# splapi - スプラトゥーンのステージ情報がとれるやつ

## APIの場所
[スプラトゥーンのステージ情報がとれるやつ（非公式）](http://splapi.retrorocket.biz/) 

## このAPIについて
2015/8/30からのスプラトゥーンのステージ情報を取得できる 個人が作成した非公式の APIです。  
[イカリング](https://splatoon.nintendo.net/schedule)の情報を使用しています。

## API利用ルール
[こちらのページを参照してください。](http://splapi.retrorocket.biz/#rule)  

## 連絡先
mail[:at:]retrorocket.biz

-------

見出し（「ステージ情報の取得」）をクリックすると、各APIの詳細が表示されます。

# Group ガチマッチのステージ情報

## 存在するすべてのステージ情報 [/gachi{?date,to,rule,map}]

### ステージ情報の取得 [GET]

date, toパラメータをどちらか使用する、もしくは組み合わせることで取得する日時の範囲を絞り込めます。  
無指定の場合すべてのデータを取得します。  
rule, mapパラメータでルールとマップを絞り込めます。  
rule, mapパラメータはカンマ（,）で区切ることでOR検索をすることができます。    
条件に合致しない場合、resultの値が空の配列であるオブジェクトを返却します。

+ Response 200 (application/json)

        {
            "result": [{
                "maps": ["ハコフグ倉庫", "シオノメ油田"],
                "rule": "ガチヤグラ",
                "end": "2015-08-31T07:00:00",
                "start": "2015-08-31T03:00:00"
            },{
                "maps": ["シオノメ油田", "ホッケふ頭"],
                "rule": "ガチヤグラ",
                "end": "2015-09-03T19:00:00",
                "start": "2015-09-03T15:00:00"
            }]
        }
        
+ Parameters
    + date: `2015-08-31T03:00:00` (string, optional) - 検索範囲の起点とする開始日時（日本時間）
    + to: `2015-09-03T19:00:00` (string, optional) - 検索範囲の終端とする終了日時（日本時間）
    + rule: `ガチヤグラ,ガチホコ` (string, optional) - ルール（日本語表記。UTF-8）
    + map: `シオノメ油田,ハコフグ倉庫` (string, optional) - 対象マップ（日本語表記。UTF-8）

## 現在開催中のステージ情報 [/gachi/now{?date,rule,map}]

### ステージ情報の取得 [GET]

dateを指定することで、指定された時刻に開催中のステージ情報を取得できます。  
dateが無指定の場合、現在時刻で開催中のステージ情報を取得します。  
rule, mapパラメータでルールとマップを絞り込めます。  
rule, mapパラメータはカンマ（,）で区切ることでOR検索をすることができます。    
条件に合致しない場合、resultの値が空の配列であるオブジェクトを返却します。

+ Response 200 (application/json)

        {
            "result": [{
                "maps": ["ハコフグ倉庫", "シオノメ油田"],
                "rule": "ガチヤグラ",
                "end": "2015-08-31T07:00:00",
                "start": "2015-08-31T03:00:00"
            }]
        }
        
+ Parameters
    + date: `2015-08-31T05:00:00` (string, optional) - 検索対象としたい日時（日本時間）
    + rule: `ガチヤグラ,ガチホコ` (string, optional) - ルール（日本語表記。UTF-8）
    + map: `シオノメ油田,ハコフグ倉庫` (string, optional) - 対象マップ（日本語表記。UTF-8）

## 次回開催されるステージ情報 [/gachi/next{?date,rule,map}]

### ステージ情報の取得 [GET]

dateを指定することで、指定された時刻の次回に開催されるステージ情報を取得できます。  
dateが無指定の場合、現在時刻を起点として、次に開催されるステージ情報を取得します。  
rule, mapパラメータでルールとマップを絞り込めます。  
rule, mapパラメータはカンマ（,）で区切ることでOR検索をすることができます。    
条件に合致しない場合、resultの値が空の配列であるオブジェクトを返却します。

+ Response 200 (application/json)

        {
            "result": [{
                "maps": ["ネギトロ炭鉱", "ヒラメが丘団地"],
                "rule": "ガチホコ",
                "end": "2015-09-04T03:00:00",
                "start": "2015-09-03T23:00:00"
            }]
        }
       
+ Parameters
    + date: `2015-09-03T19:00:00` (string, optional) - 起点とする開始日時（日本時間）
    + rule: `ガチホコ,ガチエリア` (string, optional) - ルール（日本語表記。UTF-8）
    + map: `ネギトロ炭鉱,ヒラメが丘団地` (string, optional) - 対象マップ（日本語表記。UTF-8）

## 前回開催されたステージ情報 [/gachi/prev{?date,rule,map}]

### ステージ情報の取得 [GET]

dateを指定することで、指定された時刻の前回に開催されたステージ情報を取得できます。  
無指定の場合、現在時刻を起点として、前に開催されたステージ情報を取得します。  
開始時刻・終了時刻どちらにも一致する時刻がdateで指定された場合は、終了時刻として認識されます。  
例えば、19:00がdateに指定された場合は、15:00～19:00の前に開催されたステージ情報を取得します。  
rule, mapパラメータでルールとマップを絞り込めます。  
rule, mapパラメータはカンマ（,）で区切ることでOR検索をすることができます。    
条件に合致しない場合、resultの値が空の配列であるオブジェクトを返却します。

+ Response 200 (application/json)

        {
            "result": [{
                "maps": ["ハコフグ倉庫","モンガラキャンプ場"],
                "rule": "ガチエリア",
                "end": "2015-09-02T15:00:00",
                "start": "2015-09-02T11:00:00"
            }]
        }
        
+ Parameters
    + date: `2015-09-02T19:00:00` (string, optional) - 起点とする日時（日本時間）
    + rule: `ガチエリア,ガチホコ` (string, optional) - ルール（日本語表記。UTF-8）
    + map: `ハコフグ倉庫,モンガラキャンプ場` (string, optional) - 対象マップ（日本語表記。UTF-8）

## 次回以降に開催されるすべてのステージ情報 [/gachi/next_all{?date,to,rule,map}]

### ステージ情報の取得 [GET]

dateを指定することで、指定された時刻の次に開催されるすべてのステージ情報を取得できます。  
無指定の場合、現在時刻を起点とした情報を取得します。  
toパラメータを指定することで、検索範囲となる終了日時を絞り込めます。  
rule, mapパラメータでルールとマップを絞り込めます。  
rule, mapパラメータはカンマ（,）で区切ることでOR検索をすることができます。    
条件に合致しない場合、resultの値が空の配列であるオブジェクトを返却します。

+ Response 200 (application/json)

        {
            "result": [{
                "maps": ["モズク農園","ヒラメが丘団地"],
                "rule": "ガチヤグラ",
                "end": "2015-09-01T07:00:00",
                "start": "2015-09-01T03:00:00"
            },{
                "maps": ["ハコフグ倉庫","ヒラメが丘団地"],
                "rule": "ガチヤグラ",
                "end": "2015-09-06T19:00:00",
                "start": "2015-09-06T15:00:00"
            }]
        }
    
    
+ Parameters
    + date: `2015-08-30T15:00:00` (string, optional) - 検索範囲の起点とする開始日時（日本時間）
    + to: `2015-09-08T03:00:00` (string, optional) - 検索範囲の終端とする終了日時（日本時間）
    + rule: `ガチヤグラ,ガチホコ` (string, optional) - ルール（日本語表記。UTF-8）
    + map: `ヒラメが丘団地,モズク農園` (string, optional) - 対象マップ（日本語表記。UTF-8）

## 選択日時よりも前に開催されたすべてのステージ情報 [/gachi/prev_all{?date,to,rule,map}]

### ステージ情報の取得 [GET]

dateを指定することで、指定された時刻より前に開催されたすべてのステージ情報を取得できます。  
開始時刻・終了時刻どちらにも一致する時刻がdateで指定された場合は、終了時刻として認識されます。  
例えば、19:00がdateに指定された場合は、15:00～19:00よりも前に開催されたステージ情報を取得します。  
無指定の場合、現在時刻を起点とした情報を取得します。  
toパラメータを指定することで、終了日時を絞り込めます。  
rule, mapパラメータでルールとマップを絞り込めます。  
rule, mapパラメータはカンマ（,）で区切ることでOR検索をすることができます。    
条件に合致しない場合、resultの値が空の配列であるオブジェクトを返却します。

+ Response 200 (application/json)

        {
            "result": [{
                "maps": ["デカライン高架下","シオノメ油田"],
                "rule": "ガチホコ",
                "end": "2015-08-31T15:00:00",
                "start": "2015-08-31T11:00:00"
            },
            {
                "maps": ["シオノメ油田","アロワナモール"],
                "rule": "ガチホコ",
                "end": "2015-09-01T23:00:00",
                "start": "2015-09-01T19:00:00"
            }]
        }

+ Parameters
    + date: `2015-09-07T19:00:00` (string, optional) - 起点とする終了日時（日本時間）
    + to: `2015-08-30T15:00:00` (string, optional) - 終端とする開始日時（日本時間）
    + rule: `ガチホコ,ガチヤグラ` (string, optional) - ルール（日本語表記。UTF-8）
    + map: `シオノメ油田,アロワナモール` (string, optional) - 対象マップ（日本語表記。UTF-8）
    
## ガチマッチのルール一覧 [/gachi/rules]

### ルール一覧の取得 [GET]

ガチマッチのルール一覧を配列で取得します。

+ Response 200 (application/json)

        {
         "rules": [
            "ガチエリア",
            "ガチホコ",
            "ガチヤグラ"]
        }

# Group レギュラーマッチのステージ情報

## 存在するすべてのステージ情報 [/regular{?date,to,map}]

### ステージ情報の取得 [GET]

date, toパラメータをどちらか使用する、もしくは組み合わせることで取得する日時の範囲を絞り込めます。  
無指定の場合すべてのデータを取得します。  
mapパラメータでマップを絞り込めます。  
mapパラメータはカンマ（,）で区切ることでOR検索をすることができます。    
条件に合致しない場合、resultの値が空の配列であるオブジェクトを返却します。

+ Response 200 (application/json)

        {
            "result": [{
                "maps": ["Ｂバスパーク","ヒラメが丘団地"],
                "end": "2015-08-30T23:00:00",
                "start": "2015-08-30T19:00:00"
            },
            {
                "maps": ["モズク農園","ヒラメが丘団地"],
                "end": "2015-09-01T03:00:00",
                "start": "2015-08-31T23:00:00"
            }]
        }

+ Parameters
    + date: `2015-08-30T15:00:00` (string, optional) - 検索範囲の起点とする開始日時（日本時間）
    + to: `2015-09-01T03:00:00` (string, optional) - 検索範囲の終端とする終了日時（日本時間）
    + map: `ヒラメが丘団地,Ｂバスパーク` (string, optional) - 対象マップ（日本語表記。UTF-8）

## 現在開催中のステージ情報 [/regular/now{?date,map}]

### ステージ情報の取得 [GET]

dateを指定することで、指定された時刻に開催中のステージ情報を取得できます。  
dateが無指定の場合、現在時刻で開催中のステージ情報を取得します。  
mapパラメータでマップを絞り込めます。  
mapパラメータはカンマ（,）で区切ることでOR検索をすることができます。    
条件に合致しない場合、resultの値が空の配列であるオブジェクトを返却します。

+ Response 200 (application/json)

        {
            "result": [{
                "maps": ["ネギトロ炭鉱","ヒラメが丘団地"],
                "end": "2015-08-31T07:00:00",
                "start": "2015-08-31T03:00:00"
            }]
        }

+ Parameters
    + date: `2015-08-31T05:00:00` (string, optional) - 検索対象としたい日時（日本時間）
    + map: `ネギトロ炭鉱,ヒラメが丘団地` (string, optional) - 対象マップ（日本語表記。UTF-8）

## 次回開催されるステージ情報 [/regular/next{?date,map}]

### ステージ情報の取得 [GET]

dateを指定することで、指定された時刻より次に開催されるステージ情報を取得できます。  
dateが無指定の場合、現在時刻を起点とした情報を取得します。  
mapパラメータでマップを絞り込めます。  
mapパラメータはカンマ（,）で区切ることでOR検索をすることができます。    
条件に合致しない場合、resultの値が空の配列であるオブジェクトを返却します。

+ Response 200 (application/json)

        {
            "result": [{
                "maps": ["ハコフグ倉庫","シオノメ油田"],
                "end": "2015-08-31T11:00:00",
                "start": "2015-08-31T07:00:00"
            }]
        }

+ Parameters
    + date: `2015-08-31T05:00:00` (string, optional) - 起点とする開始日時（日本時間）
    + map: `ハコフグ倉庫,シオノメ油田` (string, optional) - 対象マップ（日本語表記。UTF-8）

## 前回開催されたステージ情報 [/regular/prev{?date,map}]

### ステージ情報の取得 [GET]

dateを指定することで、指定された時刻の直前に開催されたステージ情報を取得できます。  
無指定の場合、現在時刻を起点として、前に開催したステージ情報を取得します。  
開始時刻・終了時刻どちらにも一致する時刻がdateで指定された場合は、終了時刻として認識されます。  
例えば、19:00がdateに指定された場合は、15:00～19:00の前に開催されたステージ情報を取得します。  
mapパラメータでマップを絞り込めます。  
mapパラメータはカンマ（,）で区切ることでOR検索をすることができます。    
条件に合致しない場合、resultの値が空の配列であるオブジェクトを返却します。

+ Response 200 (application/json)

        {
            "result": [{
                "maps": ["ネギトロ炭鉱","タチウオパーキング"],
                "end": "2015-08-31T15:00:00",
                "start": "2015-08-31T11:00:00"
            }]
        }

+ Parameters
    + date: `2015-08-31T19:00:00` (string, optional) - 起点とする開始日時（日本時間）
    + map: `タチウオパーキング,ネギトロ炭鉱` (string, optional) - 対象マップ（日本語表記。UTF-8）

  
## 次回以降に開催されるすべてのステージ情報 [/regular/next_all{?date,to,map}]

### ステージ情報の取得 [GET]

dateを指定することで、指定された時刻の次に開催されるすべてのステージ情報を取得できます。  
無指定の場合、現在時刻を起点とした情報を取得します。  
toパラメータを指定することで、検索範囲となる終了日時を絞り込めます。  
mapパラメータでマップを絞り込めます。  
mapパラメータはカンマ（,）で区切ることでOR検索をすることができます。    
条件に合致しない場合、resultの値が空の配列であるオブジェクトを返却します。

+ Response 200 (application/json)

        {
            "result": [{
                "maps": ["Ｂバスパーク","ヒラメが丘団地"],
                "end": "2015-08-30T23:00:00",
                "start": "2015-08-30T19:00:00"
            },
            {
                "maps": ["モズク農園","ヒラメが丘団地"],
                "end": "2015-09-01T03:00:00",
                "start": "2015-08-31T23:00:00"
            }]
        }

+ Parameters
    + date: `2015-08-30T15:00:00` (string, optional) - 検索範囲の起点とする開始日時（日本時間）
    + to: `2015-09-01T03:00:00` (string, optional) - 検索範囲の終端とする終了日時（日本時間）
    + map: `ヒラメが丘団地,Ｂバスパーク` (string, optional) - 対象マップ（日本語表記。UTF-8）

 
## 選択日時よりも前に開催されたすべてのステージ情報 [/regular/prev_all{?date,to,map}]

### ステージ情報の取得 [GET]

dateを指定することで、指定された時刻より前に開催されたすべてのステージ情報を取得できます。  
開始時刻・終了時刻どちらにも一致する時刻がdateで指定された場合は、終了時刻として認識されます。  
例えば、19:00がdateに指定された場合は、15:00～19:00よりも前に開催されたステージ情報を取得します。  
無指定の場合、現在時刻を起点とした情報を取得します。  
toパラメータを指定することで、終了日時を絞り込めます。  
mapパラメータでマップを絞り込めます。  
mapパラメータはカンマ（,）で区切ることでOR検索をすることができます。    
条件に合致しない場合、resultの値が空の配列であるオブジェクトを返却します。

+ Response 200 (application/json)

        {
            "result": [{
                "maps": ["ハコフグ倉庫","アロワナモール"],
                "end": "2015-08-31T03:00:00",
                "start": "2015-08-30T23:00:00"
            },
            {
                "maps": ["デカライン高架下","アロワナモール"],
                "end": "2015-09-06T15:00:00",
                "start": "2015-09-06T11:00:00"
            }]
        }

+ Parameters
    + date: `2015-09-07T19:00:00` (string, optional) - 起点とする終了日時（日本時間）
    + to: `2015-08-30T15:00:00` (string, optional) - 終端とする開始日時（日本時間）
    + map: `アロワナモール,ハコフグ倉庫` (string, optional) - 対象マップ（日本語表記。UTF-8）

# Group フェスマッチのステージ情報
/next. /prev, /next_all, /prev_all は使用可能ですが、フェスの性質上使用する機会が無いと思われるためドキュメントを用意していません。  
ガチ・レギュラーマッチと使用方法は同様なので、そちらのドキュメントを参照してください。

## 存在するすべてのステージ情報 [/fes{?date,to,map,team}]

### ステージ情報の取得 [GET]

date, toパラメータをどちらか使用する、もしくは組み合わせることで取得する日時の範囲を絞り込めます。  
無指定の場合すべてのデータを取得します。  
map, teamパラメータでマップとお題を絞り込めます。  
mapパラメータはカンマ（,）で区切ることでOR検索をすることができます。  
条件に合致しない場合、resultの値が空の配列であるオブジェクトを返却します。

+ Response 200 (application/json)

        {
            "result": [{
                "maps": ["デカライン高架下","シオノメ油田","タチウオパーキング"],
                "team": ["ボケ","ツッコミ"],
                "end": "2015-09-13T12:00:00",
                "start": "2015-09-12T12:00:00"
            }]
        }

+ Parameters
    + date: `2015-09-12T12:00:00` (string, optional) - 検索範囲の起点とする開始日時（日本時間）
    + to: `2015-09-13T12:00:00` (string, optional) - 検索範囲の終端とする終了日時（日本時間）
    + map: `シオノメ油田` (string, optional) - 対象マップ（日本語表記。UTF-8）
    + team: `ボケ` (string, optional) - フェスの対象お題（日本語表記。UTF-8）
    
## 現在開催中のステージ情報 [/fes/now{?date,map,team}]

### ステージ情報の取得 [GET]

dateを指定することで、指定された時刻に開催中のステージ情報を取得できます。  
dateが無指定の場合、現在時刻で開催中のステージ情報を取得します。  
map, teamパラメータでマップとお題を絞り込めます。  
mapパラメータはカンマ（,）で区切ることでOR検索をすることができます。  
条件に合致しない場合、resultの値が空の配列であるオブジェクトを返却します。

+ Response 200 (application/json)

        {
            "result": [{
                "maps": ["デカライン高架下","シオノメ油田","タチウオパーキング"],
                "team": ["ボケ","ツッコミ"],
                "end": "2015-09-13T12:00:00",
                "start": "2015-09-12T12:00:00"
            }]
        }

+ Parameters
    + date: `2015-09-12T12:00:00` (string, optional) - 検索範囲の起点とする開始日時（日本時間）
    + map: `シオノメ油田` (string, optional) - 対象マップ（日本語表記。UTF-8）
    + team: `ボケ` (string, optional) - フェスの対象お題（日本語表記。UTF-8）
    
# Group その他

## マップ一覧の取得 [/maps]

### マップ一覧の取得 [GET]

マップ一覧を配列で返却します。

+ Response 200 (application/json)

        {
            "maps":[
            "アロワナモール","キンメダイ美術館","シオノメ油田","ショッツル鉱山",
                "タチウオパーキング","デカライン高架下","ネギトロ炭鉱","ハコフグ倉庫",
                "ヒラメが丘団地","ホッケふ頭","マサバ海峡大橋","マヒマヒリゾート＆スパ",
                "モズク農園","モンガラキャンプ場","Ｂバスパーク"]
        }

## ブキ一覧の取得 [/weapons]

### ブキ一覧の取得 [GET]

ブキ一覧を配列で返却します。

+ Response 200 (application/json)

        {
            "weapons":[
            ".52ガロン",".52ガロンデコ",".96ガロン",".96ガロンデコ",
            "14式竹筒銃・乙","14式竹筒銃・甲","3Kスコープ",
            "3Kスコープカスタム","H3リールガン","(以下略)"]
        }

# Group 各種エラー

エラー発生時のステータスコード＆メッセージ。  
（わかる方向け）エラー発生時に、application/jsonでレスポンスが返ってこなかった場合、前段のリバースプロキシ（nginx）がバグっているか、後段のhypnotoadが死んでしまった可能性が高いです。

## ステータスコード＆レスポンス [/]

### ステージ情報取得時 [GET]

+ Response 404 (application/json)

    存在しないURLにアクセスした場合返却されます。
    + Body
            {"error": "Not Found."}

+ Response 500 (application/json)

    DBにアクセスしようとしてできなかった等、APIに何らかの障害が発生している場合に返却されます。  
    また、存在しない日付（2015-09-31等）を指定した場合にも発生します。

    + Body

            {"error": "Internal Server Error."}